/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarInstitucionRouteImport } from './routes/registrar-institucion'
import { Route as RegistrarDocenteRouteImport } from './routes/registrar-docente'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedPanelDocenteRouteImport } from './routes/_authenticated/panel-docente'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedEstudiantesRouteImport } from './routes/_authenticated/estudiantes'
import { Route as AuthenticatedDocentesRouteImport } from './routes/_authenticated/docentes'
import { Route as AuthenticatedAulasRouteImport } from './routes/_authenticated/aulas'
import { Route as AuthenticatedAsistenciaHistorialRouteImport } from './routes/_authenticated/asistencia-historial'
import { Route as AuthenticatedAsistenciaRouteImport } from './routes/_authenticated/asistencia'
import { Route as AuthenticatedAulasClassroomIdRouteImport } from './routes/_authenticated/aulas.$classroomId'
import { Route as AuthenticatedAsistenciaClassroomIdRouteImport } from './routes/_authenticated/asistencia.$classroomId'

const RegistrarInstitucionRoute = RegistrarInstitucionRouteImport.update({
  id: '/registrar-institucion',
  path: '/registrar-institucion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarDocenteRoute = RegistrarDocenteRouteImport.update({
  id: '/registrar-docente',
  path: '/registrar-docente',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanelDocenteRoute =
  AuthenticatedPanelDocenteRouteImport.update({
    id: '/panel-docente',
    path: '/panel-docente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstudiantesRoute =
  AuthenticatedEstudiantesRouteImport.update({
    id: '/estudiantes',
    path: '/estudiantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocentesRoute = AuthenticatedDocentesRouteImport.update({
  id: '/docentes',
  path: '/docentes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAulasRoute = AuthenticatedAulasRouteImport.update({
  id: '/aulas',
  path: '/aulas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAsistenciaHistorialRoute =
  AuthenticatedAsistenciaHistorialRouteImport.update({
    id: '/asistencia-historial',
    path: '/asistencia-historial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAsistenciaRoute = AuthenticatedAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAulasClassroomIdRoute =
  AuthenticatedAulasClassroomIdRouteImport.update({
    id: '/$classroomId',
    path: '/$classroomId',
    getParentRoute: () => AuthenticatedAulasRoute,
  } as any)
const AuthenticatedAsistenciaClassroomIdRoute =
  AuthenticatedAsistenciaClassroomIdRouteImport.update({
    id: '/$classroomId',
    path: '/$classroomId',
    getParentRoute: () => AuthenticatedAsistenciaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-docente': typeof RegistrarDocenteRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/asistencia': typeof AuthenticatedAsistenciaRouteWithChildren
  '/asistencia-historial': typeof AuthenticatedAsistenciaHistorialRoute
  '/aulas': typeof AuthenticatedAulasRouteWithChildren
  '/docentes': typeof AuthenticatedDocentesRoute
  '/estudiantes': typeof AuthenticatedEstudiantesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/panel-docente': typeof AuthenticatedPanelDocenteRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/asistencia/$classroomId': typeof AuthenticatedAsistenciaClassroomIdRoute
  '/aulas/$classroomId': typeof AuthenticatedAulasClassroomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-docente': typeof RegistrarDocenteRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/asistencia': typeof AuthenticatedAsistenciaRouteWithChildren
  '/asistencia-historial': typeof AuthenticatedAsistenciaHistorialRoute
  '/aulas': typeof AuthenticatedAulasRouteWithChildren
  '/docentes': typeof AuthenticatedDocentesRoute
  '/estudiantes': typeof AuthenticatedEstudiantesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/panel': typeof AuthenticatedPanelRoute
  '/panel-docente': typeof AuthenticatedPanelDocenteRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/asistencia/$classroomId': typeof AuthenticatedAsistenciaClassroomIdRoute
  '/aulas/$classroomId': typeof AuthenticatedAulasClassroomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-docente': typeof RegistrarDocenteRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/_authenticated/asistencia': typeof AuthenticatedAsistenciaRouteWithChildren
  '/_authenticated/asistencia-historial': typeof AuthenticatedAsistenciaHistorialRoute
  '/_authenticated/aulas': typeof AuthenticatedAulasRouteWithChildren
  '/_authenticated/docentes': typeof AuthenticatedDocentesRoute
  '/_authenticated/estudiantes': typeof AuthenticatedEstudiantesRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
  '/_authenticated/panel-docente': typeof AuthenticatedPanelDocenteRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/asistencia/$classroomId': typeof AuthenticatedAsistenciaClassroomIdRoute
  '/_authenticated/aulas/$classroomId': typeof AuthenticatedAulasClassroomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-docente'
    | '/registrar-institucion'
    | '/asistencia'
    | '/asistencia-historial'
    | '/aulas'
    | '/docentes'
    | '/estudiantes'
    | '/notificaciones'
    | '/panel'
    | '/panel-docente'
    | '/personas'
    | '/asistencia/$classroomId'
    | '/aulas/$classroomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-docente'
    | '/registrar-institucion'
    | '/asistencia'
    | '/asistencia-historial'
    | '/aulas'
    | '/docentes'
    | '/estudiantes'
    | '/notificaciones'
    | '/panel'
    | '/panel-docente'
    | '/personas'
    | '/asistencia/$classroomId'
    | '/aulas/$classroomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-docente'
    | '/registrar-institucion'
    | '/_authenticated/asistencia'
    | '/_authenticated/asistencia-historial'
    | '/_authenticated/aulas'
    | '/_authenticated/docentes'
    | '/_authenticated/estudiantes'
    | '/_authenticated/notificaciones'
    | '/_authenticated/panel'
    | '/_authenticated/panel-docente'
    | '/_authenticated/personas'
    | '/_authenticated/asistencia/$classroomId'
    | '/_authenticated/aulas/$classroomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistrarDocenteRoute: typeof RegistrarDocenteRoute
  RegistrarInstitucionRoute: typeof RegistrarInstitucionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar-institucion': {
      id: '/registrar-institucion'
      path: '/registrar-institucion'
      fullPath: '/registrar-institucion'
      preLoaderRoute: typeof RegistrarInstitucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar-docente': {
      id: '/registrar-docente'
      path: '/registrar-docente'
      fullPath: '/registrar-docente'
      preLoaderRoute: typeof RegistrarDocenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel-docente': {
      id: '/_authenticated/panel-docente'
      path: '/panel-docente'
      fullPath: '/panel-docente'
      preLoaderRoute: typeof AuthenticatedPanelDocenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estudiantes': {
      id: '/_authenticated/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof AuthenticatedEstudiantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docentes': {
      id: '/_authenticated/docentes'
      path: '/docentes'
      fullPath: '/docentes'
      preLoaderRoute: typeof AuthenticatedDocentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas': {
      id: '/_authenticated/aulas'
      path: '/aulas'
      fullPath: '/aulas'
      preLoaderRoute: typeof AuthenticatedAulasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistencia-historial': {
      id: '/_authenticated/asistencia-historial'
      path: '/asistencia-historial'
      fullPath: '/asistencia-historial'
      preLoaderRoute: typeof AuthenticatedAsistenciaHistorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/asistencia': {
      id: '/_authenticated/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AuthenticatedAsistenciaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aulas/$classroomId': {
      id: '/_authenticated/aulas/$classroomId'
      path: '/$classroomId'
      fullPath: '/aulas/$classroomId'
      preLoaderRoute: typeof AuthenticatedAulasClassroomIdRouteImport
      parentRoute: typeof AuthenticatedAulasRoute
    }
    '/_authenticated/asistencia/$classroomId': {
      id: '/_authenticated/asistencia/$classroomId'
      path: '/$classroomId'
      fullPath: '/asistencia/$classroomId'
      preLoaderRoute: typeof AuthenticatedAsistenciaClassroomIdRouteImport
      parentRoute: typeof AuthenticatedAsistenciaRoute
    }
  }
}

interface AuthenticatedAsistenciaRouteChildren {
  AuthenticatedAsistenciaClassroomIdRoute: typeof AuthenticatedAsistenciaClassroomIdRoute
}

const AuthenticatedAsistenciaRouteChildren: AuthenticatedAsistenciaRouteChildren =
  {
    AuthenticatedAsistenciaClassroomIdRoute:
      AuthenticatedAsistenciaClassroomIdRoute,
  }

const AuthenticatedAsistenciaRouteWithChildren =
  AuthenticatedAsistenciaRoute._addFileChildren(
    AuthenticatedAsistenciaRouteChildren,
  )

interface AuthenticatedAulasRouteChildren {
  AuthenticatedAulasClassroomIdRoute: typeof AuthenticatedAulasClassroomIdRoute
}

const AuthenticatedAulasRouteChildren: AuthenticatedAulasRouteChildren = {
  AuthenticatedAulasClassroomIdRoute: AuthenticatedAulasClassroomIdRoute,
}

const AuthenticatedAulasRouteWithChildren =
  AuthenticatedAulasRoute._addFileChildren(AuthenticatedAulasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAsistenciaRoute: typeof AuthenticatedAsistenciaRouteWithChildren
  AuthenticatedAsistenciaHistorialRoute: typeof AuthenticatedAsistenciaHistorialRoute
  AuthenticatedAulasRoute: typeof AuthenticatedAulasRouteWithChildren
  AuthenticatedDocentesRoute: typeof AuthenticatedDocentesRoute
  AuthenticatedEstudiantesRoute: typeof AuthenticatedEstudiantesRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
  AuthenticatedPanelDocenteRoute: typeof AuthenticatedPanelDocenteRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAsistenciaRoute: AuthenticatedAsistenciaRouteWithChildren,
  AuthenticatedAsistenciaHistorialRoute: AuthenticatedAsistenciaHistorialRoute,
  AuthenticatedAulasRoute: AuthenticatedAulasRouteWithChildren,
  AuthenticatedDocentesRoute: AuthenticatedDocentesRoute,
  AuthenticatedEstudiantesRoute: AuthenticatedEstudiantesRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
  AuthenticatedPanelDocenteRoute: AuthenticatedPanelDocenteRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistrarDocenteRoute: RegistrarDocenteRoute,
  RegistrarInstitucionRoute: RegistrarInstitucionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
