/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistrarInstitucionRouteImport } from './routes/registrar-institucion'
import { Route as IniciarSesionRouteImport } from './routes/iniciar-sesion'
import { Route as BienvenidaRouteImport } from './routes/bienvenida'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'

const RegistrarInstitucionRoute = RegistrarInstitucionRouteImport.update({
  id: '/registrar-institucion',
  path: '/registrar-institucion',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciar-sesion',
  path: '/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenidaRoute = BienvenidaRouteImport.update({
  id: '/bienvenida',
  path: '/bienvenida',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/bienvenida': typeof BienvenidaRoute
  '/iniciar-sesion': typeof IniciarSesionRoute
  '/registrar-institucion': typeof RegistrarInstitucionRoute
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-institucion'
    | '/panel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-institucion'
    | '/panel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/bienvenida'
    | '/iniciar-sesion'
    | '/registrar-institucion'
    | '/_authenticated/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BienvenidaRoute: typeof BienvenidaRoute
  IniciarSesionRoute: typeof IniciarSesionRoute
  RegistrarInstitucionRoute: typeof RegistrarInstitucionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registrar-institucion': {
      id: '/registrar-institucion'
      path: '/registrar-institucion'
      fullPath: '/registrar-institucion'
      preLoaderRoute: typeof RegistrarInstitucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciar-sesion': {
      id: '/iniciar-sesion'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenida': {
      id: '/bienvenida'
      path: '/bienvenida'
      fullPath: '/bienvenida'
      preLoaderRoute: typeof BienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BienvenidaRoute: BienvenidaRoute,
  IniciarSesionRoute: IniciarSesionRoute,
  RegistrarInstitucionRoute: RegistrarInstitucionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
